apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '7'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["192.168.96.174"],"port":80,"protocol":"HTTP","serviceName":"smartmed:keycloak","ingressName":"smartmed:keycloak","hostname":"keycloak.gnnb.com.br","allNodes":false}]
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/3xUYXPiNhD9K+1+tgGDbWx/c4Ovl0kgDGbauelkPGt5AR+ypJME00zG/70jQlIuhX5bad++t+t91iugav8gbVopIANUygyPAXiwb0UDGcxIcfnSkbDgQUcWG7QI2SugENKibaUw7ijr78SsITvQrRwwtJbToJXD1pGEaVQ3LIr9mjDyw9GE+XWdMB8Rk2m6oXQaJdB7wLEmfqJDpSCDPb0wLnEP3k3+HZqdUxiFEwwQMWQ4YilN45DVaZOm0zEl2KRR06TIRhunIrCjn8ndjVHI3LXpUNuOGoc0ipjrRpPiLUMDWeCBIU7MSu0SHVq2e7zVdd97YKlTHC2d0Bef7+ao/YUuk8JiK0gbyP56BdRbF4CxqK3f0PEX3287JbX1NSHv4NkDEscT9jzkQ/Ht7vEpf6jy2fx+AR4ckR9cApuuFdB7N5DVMi/LP59Ws/8rKefV3df8flHls9mqKMsLLJcM+U4amyWjMP5ctCpmxWJ9nz+W13R4WG8n4teLRfxU/LRYr/K79RXR0d/xdLpJw0kQsCTZJEE6GceTqCnS3+L4yyQepyljURAWnzkfim9VuX5aFdUyX3+9YBxKZYfvqxm63bmTsVLTFYov949FtcjnxQWD6aqaS7ZnO2xFtaeXwXcjBfTPHrQdbh3kxwFfnJU/dN6DbBwMgsEYrllWEzatIGOWWtYnd+2sVb+TdaFC636K4ckVZtihsaTBA2cVyJJRMnIuO0p+6GguD8K++atz4fJc+9/J36z2bzdHyf0flpkE+uePeZYHzktims6cZ6ymLdNul8/vum9pJsWm3c5RubYb2uCB27lsCLIoCD6U3q1wtrkHUrmHBzlkVh+ov95S3/f/BAAA//+WGMkg3gQAAA
    objectset.rio.cattle.io/id: 495bdc56-bea5-403c-bb8c-aaa879fe9758
  creationTimestamp: '2024-02-09T00:00:38Z'
  generation: 29
  labels:
    app: keycloak
    objectset.rio.cattle.io/hash: 4043a1aaa4ca0c9e764cb9d9972e8ad95dd9ac0f
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"keycloak"}:
                  .: {}
                  f:args: {}
                  f:env:
                    .: {}
                    k:{"name":"KEYCLOAK_ADMIN"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KEYCLOAK_ADMIN_PASSWORD"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SM_CHAIN_ADDRESS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SM_CONTRACT_ADDRESS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SM_CREDENTIALS_PASSWORD"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SM_KEY_FILE_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SM_KEY_STORE_PATH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:readinessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/opt/keycloak/data/import"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:imagePullSecrets:
                .: {}
                k:{"name":"regcred"}: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"vol-qtcs8"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                    f:optional: {}
                  f:name: {}
      manager: rancher
      operation: Update
      time: '2024-07-30T00:45:29Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2024-08-22T16:01:58Z'
  name: keycloak
  namespace: smartmed
  resourceVersion: '75806404'
  uid: e837e6a9-8228-4530-ba3d-e032fcfb4977
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keycloak
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keycloak
      namespace: smartmed
    spec:
      containers:
        - args:
            - start-dev --import-realm
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: SM_CHAIN_ADDRESS
              value: http://blockchain.smartmed.uff.br:8546
            - name: SM_CREDENTIALS_PASSWORD
              value: l4bg3n!smartmed
            - name: SM_CONTRACT_ADDRESS
              value: 6.93642537882501e+47
            - name: SM_KEY_STORE_PATH
              value: /opt/keycloak/data/keystore
            - name: SM_KEY_FILE_NAME
              value: sm_blockchain_key.json
          image: nnbguilherme/netsec:202302152300-smartmed
          imagePullPolicy: IfNotPresent
          name: keycloak
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: vol-qtcs8
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 511
            name: smartmed-realm
            optional: true
          name: vol-qtcs8
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2024-02-09T00:00:38Z'
      lastUpdateTime: '2024-02-16T02:34:45Z'
      message: ReplicaSet "keycloak-b9f67587" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2024-08-22T16:01:58Z'
      lastUpdateTime: '2024-08-22T16:01:58Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 29
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
